export const audioMap = {
  "Ready for a counting adventure?": "/assets/audio/audio_ready_for_a_counting_adventure_0.mp3",
  "Join Wei Ming on a journey to count numbers 0 to 100 through stories, simulations, and fun games!": "/assets/audio/audio_join_wei_ming_on_a_journey_to_count_numbers_0_to_1_1.mp3",
  "One morning, Wei Ming ran to the school playground. His friends were playing hopscotch! He counted the squares: 1, 2, 3... all the way to 10. \"Counting is fun!\" he laughed.": "/assets/audio/audio_one_morning_wei_ming_ran_to_the_school_playground__2.mp3",
  "After school, Wei Ming went to the market. The fruit seller had arranged apples in groups of ten. \"I have one hundred apples!\" she said. Wei Ming was amazed — that is so many! But how do you count to 100?": "/assets/audio/audio_after_school_wei_ming_went_to_the_market_the_fruit_3.mp3",
  "The next day, his teacher showed the class a trick! Instead of counting one by one, you can skip count! By 2s: 2, 4, 6, 8... By 5s: 5, 10, 15, 20... By 10s: 10, 20, 30... all the way to 100!": "/assets/audio/audio_the_next_day_his_teacher_showed_the_class_a_trick__4.mp3",
  "Wei Ming was so excited! Now he could count anything — forwards, backwards, and even by skipping numbers! \"Can we practice more?\" he asked. And so, the counting adventure began...": "/assets/audio/audio_wei_ming_was_so_excited_now_he_could_count_anythin_5.mp3",
  "Let's count with Wei Ming! 🔢": "/assets/audio/audio_let_s_count_with_wei_ming_6.mp3",
  "Hmm... how DO you count to 100? 🤔": "/assets/audio/audio_hmm_how_do_you_count_to_100_7.mp3",
  "So THAT's the secret! 💡": "/assets/audio/audio_so_that_s_the_secret_8.mp3",
  "Your turn now! 🚀": "/assets/audio/audio_your_turn_now_9.mp3",
  "If you had a jar full of marbles, how would you count them super fast?": "/assets/audio/audio_if_you_had_a_jar_full_of_marbles_how_would_you_cou_10.mp3",
  "What if there's a magical trick using groups of ten?": "/assets/audio/audio_what_if_there_s_a_magical_trick_using_groups_of_te_11.mp3",
  "What comes after ninety-nine? Can you count that high?": "/assets/audio/audio_what_comes_after_ninety_nine_can_you_count_that_hi_12.mp3",
  "The biggest number we'll explore today has a very special name!": "/assets/audio/audio_the_biggest_number_we_ll_explore_today_has_a_very__13.mp3",
  "Can you count by twos? 2, 4, 6... what comes next?": "/assets/audio/audio_can_you_count_by_twos_2_4_6_what_comes_next_14.mp3",
  "Skip counting is like taking big jumps on a number line!": "/assets/audio/audio_skip_counting_is_like_taking_big_jumps_on_a_number_25.mp3",
  "How many fingers do you have on both hands? Can you count by fives to 100?": "/assets/audio/audio_how_many_fingers_do_you_have_on_both_hands_can_you_16.mp3",
  "Your fingers are the best counting tool ever!": "/assets/audio/audio_your_fingers_are_the_best_counting_tool_ever_17.mp3",
  "If you count backwards from 10, what happens when you reach zero?": "/assets/audio/audio_if_you_count_backwards_from_10_what_happens_when_y_18.mp3",
  "Counting backwards is like a rocket countdown — 3, 2, 1, blast off!": "/assets/audio/audio_counting_backwards_is_like_a_rocket_countdown_3_2__19.mp3",
  "Let's find out together!": "/assets/audio/audio_let_s_find_out_together_20.mp3",
  "Click the squares to count. Each filled square equals one!": "/assets/audio/audio_click_the_squares_to_count_each_filled_square_equa_21.mp3",
  "Try counting to different numbers! There are no wrong answers.": "/assets/audio/audio_try_counting_to_different_numbers_there_are_no_wro_22.mp3",
  "One ten and some ones make the teen numbers!": "/assets/audio/audio_one_ten_and_some_ones_make_the_teen_numbers_23.mp3",
  "Slide the control to count the teen numbers!": "/assets/audio/audio_slide_the_control_to_count_the_teen_numbers_24.mp3",
  "Choose to count by twos, fives, or tens and watch the numbers light up!": "/assets/audio/audio_choose_to_count_by_twos_fives_or_tens_and_watch_th_26.mp3",
  "Click any number to hear it! Explore patterns in the chart.": "/assets/audio/audio_click_any_number_to_hear_it_explore_patterns_in_th_27.mp3",
  "Notice how each row ends with a number ending in zero!": "/assets/audio/audio_notice_how_each_row_ends_with_a_number_ending_in_z_28.mp3",
  "Great job!": "/assets/audio/audio_great_job_29.mp3",
  "What number comes after 29?": "/assets/audio/audio_what_number_comes_after_29_30.mp3",
  "Count by 5s: 5, 10, 15, ___. What comes next?": "/assets/audio/audio_count_by_5s_5_10_15_what_comes_next_31.mp3",
  "Which is more: 47 or 74?": "/assets/audio/audio_which_is_more_47_or_74_32.mp3",
  "How do you feel about counting?": "/assets/audio/audio_how_do_you_feel_about_counting_33.mp3",
  "Be honest — every answer is great!": "/assets/audio/audio_be_honest_every_answer_is_great_34.mp3",
  "Journey Complete!": "/assets/audio/audio_journey_complete_35.mp3"
};
export default audioMap;